### ISSUE TITLE
[1.16.3] Mixin conflict

### ISSUE THREAD

**Issue by kwpugh** [MaroonAngel/Cultivation#1]
Hi,

It looks like you are using the identical mixin for recipe remainder from two of my mods (VeggieWay and Resourceful Tools) and it causes the following error:  Method overwrite conflict for getRemainingStacks in cultivation.mixins.json:ShapelessRecipeMixin, previously written by com.kwpugh.pugh_lib.mixin.RecipeRemainderMixin. Skipping method.

The result is your mixin does not run and your knife is consumed in the crafting table when used.

**Comment by MaroonAngel** [comment]
Hi kwpugh! 
Thank you for letting me know. I'm still a beginner with developing fabric mods so I'm not quite sure how to solve that at the moment, but as soon as I figure it out I'll update this thread and upload the new version :)

**Comment by MaroonAngel** [comment]
I've removed those items entirely in favor of other functionality, so the conflict should be resolved.
